apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-probe
spec:
  containers:
  - image: kattorzeh/kubia-unhealthy
    name: bad-kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080